#' Do linear interpolation of measurements generate daily values
#' @param data_frame The input data frame
#' @param date_col The name of the date column
#' @param measurement_cols The list of names of the measurement column(s)
#' @return The dataframe with daily measurements generated by linear interpolation
interpolate_measurements <- function(data_frame, date_col, measurement_cols) {
  data_frame <- as.data.frame(data_frame)
  data_frame$date_2 <- as.Date(data_frame[, date_col])
  daily_dates <- data.frame(
    date = seq.Date(
      min(data_frame$date_2),
      max(data_frame$date_2),
      by = "days"
    )
  )
  data_frame_interp <- data_frame %>%
    mutate(is_observation = T) %>%
    full_join(daily_dates, by = setNames(nm = date_col, "date")) %>%  # https://stackoverflow.com/questions/28399065/dplyr-join-on-by-a-b-where-a-and-b-are-variables-containing-strings
    arrange(!!sym(date_col)) %>%
    mutate(across(all_of(measurement_cols), ~ zoo::na.approx(.x, na.rm = F)))
  return(data_frame_interp)
}
