# This script is to estimate a shedding load distribution for influenza based on the literature

library(xlsx)
library(ggplot2)
library(dplyr)
library(tidyr)

# Load data
data <- read.xlsx("data/data_used_in_manuscript/shedding_profile_data.xlsx", sheetIndex = 2)
carrat2008 <- read.csv("data/data_used_in_manuscript/shedding_profile_carrat_2008.csv")
fit <- read.csv("data/raw_data/shedding_profile_fit.csv")  # generated by get_shedding_load_distribution_resp.R

# Annotate data
data_cleaned <- data %>% group_by(specimen.type) %>%
    mutate(sample_type = case_when(
        specimen.type == "nose-throat swab" ~ "respiratory",
        specimen.type == "sputum" ~ "respiratory",
        specimen.type == "faeces" ~ "stool")) %>%
    mutate(title_2 = paste(author_year, title, sep = ": ")) %>%
    mutate(third_sd = 3 * sd(measurement)) %>%
    mutate(outlier = case_when(measurement > third_sd ~ T, T ~ F)) %>%
    mutate(measurement.day = as.numeric(measurement.day))

# Filter data
data_filtered <- data_cleaned %>%
    filter(
        units != "Cycle threshold",
        !is.na(measurement.day))

# Get study-specific detection limits
detection_limits <- data_filtered %>%
    group_by(title_2, sample_type, influenza.type) %>%
    summarize(
        detection_limit = detection.limit[1],
        n_limits = length(unique(detection.limit))
    )

# Format Carrat 2008 summary data
carrat_clean <- carrat2008 %>%
    mutate(measurement = 10^log_viral_titer) %>%
    mutate(measurement.day = days_after_innoculation) %>%
    mutate(title_2 = "Carrat 2008: Time Lines of Infection and Disease in Human Influenza: A Review of Volunteer Challenge Studies")

# Plot data
max_days <- 36
ggplot(data = data_filtered, aes(x = measurement.day, y = log10(measurement), color = title_2)) +
    geom_point(shape = 1) +
    geom_hline(data = detection_limits, aes(yintercept = log10(detection_limit), color = title_2, linetype = "Detection limit")) +
    # geom_text(aes(label = patient)) +
    # geom_line(data = carrat_clean, aes(x = measurement.day - 1)) +
    facet_grid(influenza.type ~ sample_type, scales = "free_y") +
    theme_bw() +
    theme(legend.position = "bottom") +
    scale_x_continuous(breaks = seq(0, max_days, 5), limits = c(-3, max_days)) +
    scale_y_continuous(limits = c(0, NA)) +
    scale_color_discrete(labels = function(x) stringr::str_wrap(x, width = 70)) +
    scale_linetype_manual(values = c("Detection limit" = "dashed"), name = "") +
    guides(color = guide_legend(ncol = 1, byrow = TRUE, title = element_blank(), keyheight = 0.5)) +
    theme(legend.text = element_text(size = 8), legend.spacing.x = unit(0, "cm"), legend.spacing.y = unit(0, "cm")) +
    labs(y = "log10 Viral RNA", x = "Days since symptom onset")
ggsave("figures/shedding_load_data.png", width = 5.5, height = 6, units = "in")

# Format gamma distribution actually used
days <- seq(from = 0, to = range(data_filtered$measurement.day)[2], by = 0.01)
used_dist_tmp <- data.frame(
    measurement.day = days,
    measurement = dgamma(x = days, shape = fit$shape[1], scale = fit$scale[1]),
    title_2 = "Gamma fit to Carrat 2008 with MLE"
) %>% bind_rows(data.frame(
    measurement.day = days,
    measurement = dgamma(x = days, shape = fit$shape[2], scale = fit$scale[2]),
    title_2 = "Gamma fit to Carrat 2008 with moments"
))
used_dist <- bind_rows(
    used_dist_tmp %>% mutate(influenza.type = "IAV"),
    used_dist_tmp %>% mutate(influenza.type = "IBV"),
    used_dist_tmp %>% mutate(influenza.type = "Pandemic H1N1 2009")
)

# Plot data with (scaled) gamma distribution
max_days <- 36
sf <- 1E9
ggplot(data = data_filtered, aes(x = measurement.day, y = log10(measurement))) +
    geom_point(shape = 1, aes(color = title_2)) +
    # geom_line(data = carrat_clean, aes(x = measurement.day - 1)) +
    geom_line(data = used_dist %>% filter(title_2 == "Gamma fit to Carrat 2008 with MLE") %>% mutate(measurement = measurement * sf, measurement.day = measurement.day - 2)) +
    facet_grid(influenza.type ~ sample_type, scales = "free_y") +
    theme_bw() +
    theme(legend.position = "bottom") +
    scale_x_continuous(breaks = seq(0, max_days, 5), limits = c(-3, max_days)) +
    scale_y_continuous(limits = c(0, NA), oob = scales::oob_keep) +
    scale_color_discrete(labels = function(x) stringr::str_wrap(x, width = 95)) +
    guides(color = guide_legend(ncol = 1, byrow = TRUE, title = element_blank(), keyheight = 0.5)) +
    theme(legend.text = element_text(size = 8)) +
    labs(y = "log10 Viral RNA", x = "Days since symptom onset")
ggsave("figures/shedding_load_data_with_fit.png", width = 5.5, height = 6, units = "in")
