# This workflow is to re-generate case-based Re estimates

name: calculate-case-based-re

on:
  push:
    branches: 
      - 'master'
    paths:
      - 'data/clean_data_cases_che.csv'  # workflow only runs with new data is pushed

jobs:
        
  estimate-case-re:
    runs-on: macOS-latest  
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  
    steps:
      # Load repo and install R, package dependencies
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2  # install (possibly cached) dependencies from DESCRIPTION
      
      # Run R script
      - name: Estimate Re
        run: Rscript estimate_re/estimate_confirmed_case_re.R
    
      # Commit new files to data folder
      - name: Commit files
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git add app/data/confirmed_case_re_estimates.csv
          git commit -am "GH ACTION estimate-re $(date)"
          git push origin master
          