# This workflow is to re-generate Re estimates each day

name: calculate-re-daily

on: [push]  # TODO: switch to daily
  # schedule:
  # - cron: "0 0 * * *"

jobs:
  estimate-re:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  
    steps:
      # Load repo and install R, package dependencies
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2  # install (possibly cached) dependencies from DESCRIPTION
      
      # Run R script
      - name: Estimate Re
        run: Rscript estimate_re/estimate_wastewater_re.R
    