# This workflow is to re-generate wastewater Re estimates

name: calculate-ww-re

on:
  push:
    branches: 
      - 'master'
    paths:
      # Only run when a relevant file is updated
      - 'data/clean_data_bs.csv'
      - 'data/clean_data_ge_zh.csv'
      - '.github/workflows/estimate_ww_re.yaml'
      - 'R/estimate_wastewater_re.R'

jobs:
        
  estimate-ww-re:
    runs-on: macOS-latest  
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  
    steps:
      # Load repo and install R, package dependencies
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2  # install (possibly cached) dependencies from DESCRIPTION
      
      # Run R script
      - name: Estimate Re
        run: Rscript R/estimate_wastewater_re.R
    
      # Commit new files to data folder
      - name: Commit files
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git add app/data/ww_loads.csv
          git add app/data/ww_re_estimates.csv
          git commit -am "GH ACTION calculate-ww-re $(date)"
          git push origin master
          